#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#

bindkey '^R' history-incremental-search-backward

fpath=(/usr/local/share/zsh-completions $fpath)

unsetopt correct
unsetopt correctall
DISABLE_CORRECTION="true"

export GITHUB_TOKEN=a4f2612586eb048000ce5a9361d50855cd5c31e9

alias pr=~/bin/pr
alias cat=bat -p
export BAT_PAGER=""
